<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="QA Automation challange"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="11.221">
    <properties></properties>

            <testcase
                name="test"
                time="11.221"
                classname="BaseUtilities.EmailServices">

            <failure type="org.apache.commons.mail.EmailException" message="Sending the email to the following server failed : smtp.mail.yahoo.com:465">
                <![CDATA[org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.mail.yahoo.com:465
                org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)org.apache.commons.mail.Email.send(Email.java:1496)BaseUtilities.EmailServices.test(EmailServices.java:27)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:334)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)org.testng.SuiteRunner.run(SuiteRunner.java:240)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)org.testng.TestNG.runSuitesLocally(TestNG.java:1123)org.testng.TestNG.run(TestNG.java:1031)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
                    Caused by: javax.mail.AuthenticationFailedException: 535 5.7.0 (#AUTH005) Too many bad auth attempts.

                    com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:932)com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:843)com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:748)javax.mail.Service.connect(Service.java:388)javax.mail.Service.connect(Service.java:246)javax.mail.Service.connect(Service.java:195)javax.mail.Transport.send0(Transport.java:254)javax.mail.Transport.send(Transport.java:124)org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)org.apache.commons.mail.Email.send(Email.java:1496)BaseUtilities.EmailServices.test(EmailServices.java:27)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:334)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)org.testng.SuiteRunner.run(SuiteRunner.java:240)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)org.testng.TestNG.runSuitesLocally(TestNG.java:1123)org.testng.TestNG.run(TestNG.java:1031)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
                ]]>
            </failure>
    </testcase>


</testsuite>
