<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="QA Automation challange"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="29.312">
    <properties></properties>

            <testcase
                name="fullTask"
                time="29.312"
                classname="Scenarios">

            <failure type="java.lang.AssertionError" message="Example of failen test case!
Expected: &lt;2&gt;
     but: was &lt;78&gt;">
                <![CDATA[java.lang.AssertionError: Example of failen test case!
Expected: <2>
     but: was <78>
                BaseUtilities.CustomAssert.assertThat(CustomAssert.java:48)Pages.Careers.sixthTask(Careers.java:191)Scenarios.fullTask(Scenarios.java:27)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:334)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)org.testng.SuiteRunner.run(SuiteRunner.java:240)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)org.testng.TestNG.runSuitesLocally(TestNG.java:1123)org.testng.TestNG.run(TestNG.java:1031)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


</testsuite>
